### ISSUE TITLE
memory regions?

### ISSUE THREAD

**Issue by spamwax** [jgouly/mkl27z-rs#1]
Hi there,

What are the memory region addresses for this MC?
I got an NXP FRDM-KL25Z and I am not sure how find information such as

```
MEMORY
{
  /* NOTE K = KiBi = 1024 bytes */
  FLASH : ORIGIN = 0x08000000, LENGTH = 256K
  RAM : ORIGIN = 0x20000000, LENGTH = 40K
}
```

**Comment by jgouly** [comment]
Mine are defined here: https://github.com/jgouly/mkl27z-rs/blob/master/src/mkl27z.ld#L3 Although mine isn't right. It says I have 8K, but it should be 32K.

If you get the reference manual for the MKL25, it should have a section called 'SRAM'. It should be explained in there.
